apiVersion: v1
kind: Service
metadata:
  name: blog-app-service
spec:
  selector:
    app: blog-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 32000
  type: NodePort
