apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-persistant-volume
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  hostPath:
    path: "/mnt/data/mongodb"
